language: python
python: 3.6

install:
  - pip install tox
script:
  - tox -e $TOX_ENV

matrix:
  include:
    - env: TOX_ENV=lint
    - python: 3.6
      env: TOX_ENV=py36
      after_success:
        - pip install codecov
        - codecov -v
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.8
      env: TOX_ENV=py38
